%YAML:1.0

base_config: "../base.yaml"

sdf_iter_step: 5000
gs_iter_step: 3000

preload: 1 # 0: disable; 1: enable # accelerate the loading process but will cost more memory
llff: 1 # 0: disable; 1: enable; every 8 frame will be used for evaluation

# rosrun neural_mapping neural_mapping_node train \
#   src/GS-SDF/config/colmap/colmap_example.yaml \
#   src/GS-SDF/data/my_bag/data_0621_object/


# dataset_type
#   Replica = 0,
#   R3live = 1,
#   NeuralRGBD = 2,
#   KITTI = 3,
#   FastLivo = 4,
#   Oxford Spires = 5,
#   Colmap = 6
dataset_type: 6
camera_path: "sparse/0/cameras.txt"
color_path: "images"
color_type: ".png"
mask_path: "masks"
color_pose_path: "sparse/0/images.txt"
color_pose_type: 4
color_pose_w2c: 1
depth_path: "depths"
depth_pose_path: "sparse/0/depths.txt"
depth_pose_type: 4
depth_type: 1 # 0: image; 1: ply; 2: bin; 3: pcd

sh_degree: 3
bck_color: 0 # 0: black background; 1: white background; 2: discourage transparancy; degenerate results

frame_rate: 10
min_range: 0.01
max_range: 100
ds_pt_num: 200   # 10000 # downsampled point number
max_pt_num: 1000000

outlier_remove: 0 # unnecessary for static scenes
outlier_dist: 0.05
outlier_removal_interval: 2000

# scene config
leaf_sizes: 0.2 # 根据物体大小要调整，这个是marching cubes的体素大小，对于小场景，如一个小物体，就要调小一点
bce_sigma: 0.1 # if get floaters, increase this value

# visualization
vis_resolution: 0.1 # better no more than leaf_sizes or will miss faces
export_resolution: 0.04
fps: 10

# This is the camera configuration; scale adjusts training resolution (e.g. 0.5 = half resolution).
# Intrinsics are loaded automatically from camera_path (cameras.txt).
camera:
   scale: 0.5

map:
   map_size: 300
